version: '3.1'

services:

  api:
    build: .
    hostname: tag-onboarding-api
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      APP_NAME: tag-onboarding-api
      APP_ENV: prod
      CONFIG_PATH: /app/configs
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: onboardingdb
    volumes:
      - mongo_data_onboarding:/data/db
volumes:
  mongo_data_onboarding:
    driver: local
